# Generated by Django 4.0.5 on 2022-10-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_livro_quantidade_alter_autor_email_alter_autor_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(related_name='livros', to='core.autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editora', to='core.editora'),
        ),
    ]
